name: publish client

on:
  release:
    types: [published]

jobs:
  publish-client-for-typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"

      - name: publish to npm
        run: npm version ${GITHUB_REF##*/} && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
